-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: d8a44784fcf4920ac11d10b9c12549a6f73de67a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        - -v
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        args:
        - --max-line-length=100
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b7f5d468c67c3c4a6ea7cdf68c40778095b0f19b
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: git://github.com/guykisel/prospector-mirror
    sha: 41e0faa3d8b999830ed22d508db33f920d189996
    hooks:
    -   id: prospector
        args:
        - -o=pylint
        - --strictness=verylow
